server:
  port: 9092

spring:
  application:
    name: contract-tariff-service
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://43.200.145.199:5432/scm
    characterEncoding: UTF-8
    username: admin
    password: 1234
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: "true"
        show-sql: "true"
    hibernate:
      ddl-auto: update
    generate-ddl: true

jwt:
  header: Authorization
  expTime: 864000000
  secret_key: my-very-secret-keymy-very-secret-keymy-very-secret-keymy-very-secret-keymy-very-secret-key

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.37.155.50:8761/eureka